String getLanguage(String keyLetter) {
  return appLanguage[keyLetter].toString();
}

Map<String, String> appLanguage = AppLanguage.englishLanguage;

class AppLanguage {
  static const Map<String, String> englishLanguage = {
    'DarkMode': 'Dark',
    'LightMode': 'Light',
    'Arabic': 'العربية',
    'English': 'English',
    'Resend': 'Resend',

    "PhoneNumber": "Phone Number",
    "Password": "Password",
    "ForgotPassword": "Forgot Password ?",
    "incorrect_pass": "Incorrect Password",
    "Login": "Login",

    "otp": "OTP",
    "delete_beneficiary_done": "Beneficiary Deleted",
    "skip": "Skip",
    "Dont_have_account": "Don't have account",
    "Register Now": "Register Now",

    "gallery": "Gallery",
    "Camera": "Camera",
    "submit_answer": "Submit Answer",
    "arabic": "عربي",
    "notification": "Notifications",
    "no_beneficiary": "You have no beneficiaries",
    "birthday": "Date of birth",
    "download_medical_report": "Download Medical Report",
    "Choose_beneficiary": "Choose the beneficiary :",
    "english": "English",
    "personal_info": "Personal info",

    "yes": "Yes",
    "share": "Share",
    "no": "No",
    "edit_profile_info": "Edit Profile Info",
    "close": "Close",

    "alert": "Alert!",
    "cancel": "Cancel",
    "edit": "Edit",
    "delete": "Delete",
    "logout": "LogOut",

    "card_number": "Card Number",
    "Card_information": "Card information",
    "Cardholder_name": "Cardholder name",
    "Last_Payment": "Last Payment",
    "subscription_number": "subscription number",

    "Confirm_Password": "Confirm Password",
    "Therapeutic_plan": "Therapeutic plan",
    "herapeutic_sessions": "Therapeutic sessions",
    "subscription_valid_date": "Your subscription is valid until the date",
    "Addbeneficiary": "Add a beneficiary",

    "male": "male",
    "female": "female",
    "new_pass": "New Password",
    "rewrite_new_pass": "RewRite New Password ",
    "beneficiary_name": " Beneficiary Name",

    "Wouldlogout": "Would you like to logout?",
    "allfiledrequired": "please Fill All Required filled",
    "Enter_Verification_code": "Enter Verification code",
    "Verification_code_that_it_by_sms": "Verification code that it by sms",
    "having_trouble_with_code":
        "Are you having trouble with the confirmation code",

    "Send": "Send",
    "description": "Description :",
    "upload_medical_report": "Upload Medical Report",
    "Pathological_case": "Pathological case",
    "req_date": "Request Date:",

    "call_support": "Call The Support",
    "Subscription_renewal": "Subscription Renewal",
    "ok": "OK",
    "can": "Can",
    "notcan": "Not Can",

    "sometimes": "Sometimes",
    "something_wrong": "Something Wrong Please Try Again Later",
    "change_pass": "Change Password",
    "oldpass": "Old Password",
    "gender": "Gender",

    "pass_change_done": "Password Updates",
    "answer_all_question": "Answer all the questions and try again",
    "answer_send": "All answers have been sent",
    "not_have_Reviews": "Not Have Reviews",
    "please_wait": "Please Wait ...",

    "account_suspended": "Your account is suspended",
    "more_info": "Please contact the number for more information",
    "video_updated": "The video has been uploaded successfully",
    "sure_delet": "Are you Sure to delete",
    "subscription_has_not_expired ":
        "the subscription has not expired to renew please wait for subscription expire",

    "or": "OR",
    "WrongOTP": "Wrong otp code, please try again",
    "norepoert": "Not Have Any Medical Report",
    "validemail": "Please enter the valid email",
    "pay_now": "Pay Now",

    "Upload_Image": "Upload_image",
    "notes": "Notes",
    "videos": "Videos",
    "upload_video": "Upload Video",
    'continue': 'Continue',

    "Reviews": "Reviews",
    "beneficiary": "Beneficiary",
    "message": "Message",
    "save": "Save",
    "enter_phone_number": "Please enter your phone number",

    "Select_child_download_report":
        "Select your child to download his/her report",
    "mediacl_report": "Medical Report",
    "pass6digit": "The password must contain at least 6 characters or more",
    "Resend Verification Code": "Resend Verification Code",
    "Do you have problem in verification code":
        "Do you have problem in verification code",

    "phonenumberorpassinvalid": "Phone Number or Password Invalid",
    "Ring for help": "Ring for help",
    "haveaccountalready": "Do you have an account? Login",
    "First Name": "First Name",
    "name": "Name",
    "dob": "Date of birth",

    "Email": "Email",
    "language": "language",
    "my_file": "My File",
    "contact_us": "Contact Us",
    "City": "City",

    "help_center": "Help Center",
    "update_info": "Update Info",
    "Registerpage": "Register Page",
    "mainpage": "Main Page",
    "age": "Age",
    "add_beneficiary": "Add Beneficiary",

    "welcome_name": " Welcome to",
    "Rewrite Password": "Rewrite Password",
    "Register": "Register",
    "Do you have account ?": "Do you have account ?",
    "New Password": "New Password",

    "Passwords_not_match": "Passwords do not match",
    "Rewrite new Password": "Rewrite new Password",
    "Done": "Done",
    "call_help_center": "Call  Help Center",
    'Phone number is incorrect': 'Phone number is incorrect',
    "medical_attachments": "Medical Attachments",
    "card_info": "Card Info",
    "card_holder_name": "Card Holder Name",
    "success": "Operation Success !",
    "8letter": "Password Can't To Be Less Than 8 letter",
    "25Letter": "Password Can't To Be Larger Than 25 Letter",
    'SignUp': 'Sign Up',
    "UserNameCan'tToBeLargerThan40Letter":
        "User Name Can't To Be Larger Than 40 Letter",
    "UserNameCan'tToBeLessThan4Letter":
        "User Name Can't To Be Less Than 4 Letter",

    "EmailCan'tToBeLargerThan100Letter":
        "Email Can't To Be Larger Than 100 Letter",
    "EmailCan'tToBeLessThan4Letter": "Email Can't To Be Less Than 4 Letter",
    'We just sent a code to ': 'We just sent a code to ',
    'Enter the code here and we can continue!':
        'Enter the code here and we can continue!',
    "Didn't receive the code? ": "Didn't receive the code? ",

    "Make sure of the city's name": "Make sure of the city's name",
    // '':'',
    // '':'',
    // '':'',
    // '':'',

    // '':'',
    // '':'',
    // '':'',
    // '':'',
    // '':'',

    // '':'',
    // '':'',
    // '':'',
    // '':'',
    // '':'',

    // '':'',
    // '':'',
    // '':'',
    // '':'',
    // '':'',
  };

  static const Map<String, String> arabicLanguage = {
    'DarkMode': 'المعتم',
    'LightMode': 'النهاري',
    'Arabic': 'العربية',
    'English': 'English',
    "PhoneNumber": "رقم الهاتف",
    "enter_phone_number": "يرجى إدخال رقم الهاتف الخاص بك",
    "Password": "كلمة المرور",
    "ForgotPassword": "هل نسيت كلمة المرور ؟",
    "change_pass": "تغير كلمة المرور",
    "skip": "تخطي",
    "arabic": "عربي",
    "english": "English",
    "pass_change_done": "تم تغير كلمة المرور",
    "subscription_has_not_expired ":
        "لم تنتهي صلاحية الاشتراك للتجديد ، يرجى الانتظار حتى انتهاء صلاحية الاشتراك",
    "can": "أستطيع",
    "notcan": "لا أستطيع",
    "sometimes": "احيانا",
    "birthday": "تاريخ الميلاد",
    "notes": "الملاحظات",
    "allfiledrequired": "يرجى ملئ جميع المعلومات المطلوبة",
    "incorrect_pass": "كلمة مرور خاطئة",
    "delete_beneficiary_done": "تم حذف المستفيد",
    "something_wrong": "حدث خطأ ما الرجاء المحاولة لاحقا",
    "yes": "نعم",
    "validemail": "يرجى ادخال بريد الكتروني صالح",
    "no": "لا",
    "Wouldlogout": "هل أنت متأكد من تسجيل الخروج",
    "success": "تمت العملية بنجاح",
    "Login": "دخول",
    "alert": "تنبيه!",
    "ok": "موافق",
    "pass6digit": "يجب ان يحتوي الباسورد على 6 خانات واكثر عالاقل",
    "Dont_have_account": "لا تمتلك حساب ؟",
    "haveaccountalready": "هل تمتلك حساب ؟ دخول",
    "edit": "تعديل",
    "Passwords_not_match": "كلمتا المرور لا تتطابقات",
    "no_beneficiary": "لا يوجد مستفيدين لديك",
    "add_beneficiary": "أضف مستفيد",
    "delete": "حذف",
    "sure_delet": "هل متأكد من حذف ",
    "edit_profile_info": "تعديل الصفحة الضخصية",
    "Addbeneficiary": "اضف مستفيد",
    "call_help_center": "الاتصال بمركز المساعدة",
    "welcome_name": "اهلا وسهلا بك",
    "cancel": "الغاء",
    "notification": "الاشعارات",
    "mediacl_report": "الملف الطبي",
    "Select_child_download_report": "اختر طفلك لتنزيل ملفه الطبي",
    "Choose_beneficiary": " اختر المستفيد :",
    "Register": "سجل الان",
    "download_medical_report": "تنزيل التقرير الطبي",
    "Enter_Verification_code": "ادخل رمز التأكيد",
    "Verification_code_that_it_by_sms":
        "رمز التأكيد الذي تم ارساله برسالة قصيرة",
    "having_trouble_with_code": "هل تواجه مشكلة في رمز التأكيد",
    "call_support": "اتصل بالدعم الفني",
    "mainpage": "الرئيسية",
    "male": "ذكر",
    "female": "انثى",
    "update_info": "تحديث الملومات",
    "gallery": "المعرض",
    "Camera": "الكاميرا",
    "new_pass": "كلمة السر الجديدة",
    "rewrite_new_pass": "اعادة كتابة كلمة السر",
    "Done": "تم",
    "subscription_number": "اشتراك رقم",
    "otp": "رمز التأكيد",
    "WrongOTP": "رمز تاكيد خاطئ يرجى اعادة المحاولة ",
    "contact_us": "تواصل معنا",
    "name": "الاسم",
    "Email": "البريد الالكتروني",
    "message": "الرسالة",
    "or": "او",
    "gender": "الجنس",
    "save": "حفظ",
    "City": "المدينة",
    "Registerpage": "التسجيل",
    "Confirm_Password": "اعادة كلمة السر",
    "my_file": "ملفي",
    "Last_Payment": "الدفعات السابقة",
    "language": "اللغة",
    "help_center": "مركز المساعدة",
    "share": "مشاركة",
    "logout": "خروج",
    "beneficiary_name": "اسم المستفيد",
    "age": "العمر",
    "Pathological_case": "الحالة المرضية",
    "dob": "تاريخ الولادة",
    "medical_attachments": "إرفاقات طبية",
    "phonenumberorpassinvalid": "رقم الهاتف او كلمة المرور غير صحيحة",
    "upload_medical_report": "ارفاق التقارير الطبية",
    "norepoert": "ليس لديك أي تقرير طبي",
    "Upload_Image": "تحميل صورة",
    "Card_information": "معلومات البطاقة",
    "Cardholder_name": "اسم حامل البطاقة",
    "oldpass": "كلمة المرور القديمة",
    "account_suspended": "حسابك موقوف ",
    "more_info": "يرجى التواصل مع الرقم لمزيد من المعلومات",
    "beneficiary": "المستفيد",
    "videos": "الفيديوهات",
    "answer_all_question": "أجب على كل الاسئلة ثم اعد المحاولة مرة اخرى",
    "Reviews": "التقيمات",
    "answer_send": "تم ارسال جميع الاجابات ",
    "Therapeutic_plan": "الخطة العلاجية",
    "card_info": "معلومات البطاقة",
    "card_holder_name": "اسم حامل البطاقة",
    "submit_answer": "إرفاق الاجابات",
    "not_have_Reviews": "لا يوجد تقيمات",
    "video_updated": "تم رفع  الفيديو بنجاح",
    "herapeutic_sessions": "الجلسات العلاجية",
    "subscription_valid_date": "اشتراكك صالح حتى التاريخ",
    "Subscription_renewal": "تجديد الاشتراك",
    "pay_now": "ادفع الان",
    "description": "الوصف :",
    "req_date": "التاريخ المطلوب :",
    "upload_video": "تحميل فيديو",
    "card_number": "رقم البطاقة",
    "Send": "ارسل",
    "personal_info": "المعلومات الشخصية",
    "please_wait": "يرجى الانتظار ....",
    "close": "اغلاق",
    'Phone number is incorrect': 'رقم الهاتف غير صحيح',
    "8letter": "لا يمكن قبول كلمة السر الضعيفة اقل من ٨ حروف",
    "25Letter": "كلمة السر طويلة جدا اكثر من ٢٥ حرف",
    'SignUp': 'إنشاء حساب',
    "UserNameCan'tToBeLargerThan40Letter":
        "اسم المسخدم طويل جدا اكثر من ٤٠ حرف",
    "UserNameCan'tToBeLessThan4Letter": "اسم المستخدم قصير جدا اقل من ٤ حروف",
    "EmailCan'tToBeLargerThan100Letter":
        "البريد الالكتروني طويل جدا اكثر من ١٠٠ حرف",
    "EmailCan'tToBeLessThan4Letter": "البريد الالكتروني قصير اقل من ٤ حروف",
    'continue': 'إرسال',
    'We just sent a code to ': 'تم إرسال الرسالة إلى رقم',
    'Enter the code here and we can continue!':
        'ادخل رمز التحقق واضغط على استمر',
    'Resend': 'إعادة إرسال رمز التأكد',
    "Didn't receive the code? ":
        "هل تواجه مشكله في رمز التحقق\nاتصل بنا للمساعدة\n+971",
    "Make sure of the city's name": "تأكد من اسم المدينة",
  };
}
